package JDBC;

import java.sql.PreparedStatement;

import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;

import Interfaces.DentistManager;
import POJO.Dentists;

public class JDBCDentistManager implements DentistManager{

	private JDBCManager manager;
	
	public JDBCDentistManager(JDBCManager m) {
		
		this.manager=m;
	}

	//The id variable is not included as a parameter in  INSERT INTO because it is
	//generated by the database with an AUTOINCREMENT
	@Override
	public void addDentist(Dentists d) throws Exception {
		
		String sql= "INSERT INTO dentist (name, bank_account, email, mobile) "
				+ " VALUES(?,?,?,?)";
		
			PreparedStatement prep= manager.getConnection().prepareStatement(sql);
		
			prep.setString(1, d.getName());
			prep.setString(2, d.getBank_account());
			prep.setString(3, d.getDoc_email());
			prep.setInt(4, d.getDoc_mobile());

			prep.executeUpdate();
	}

	@Override
	public void deleteDentist(int dentistId) throws Exception {

		String sql= "DELETE FROM dentist "
				+ " WHERE id= ?";
		
		
		PreparedStatement prep= manager.getConnection().prepareStatement(sql);
	
		prep.setInt(1, dentistId);

		prep.executeUpdate();
	}

	@Override
	public void updateDentist(Dentists d) throws Exception {
		
		String sql= "UPDATE dentist "
				+ "SET name=?, bank_account=?, email=?, mobile=?"
				+ "WHERE id= ?";
		
		PreparedStatement prep= manager.getConnection().prepareStatement(sql);
		
		prep.setString(1, d.getName());
		prep.setString(2, d.getBank_account());
		prep.setString(3, d.getDoc_email());
		prep.setInt(4, d.getDoc_mobile());
		prep.setInt(5, d.getDoc_id());

		prep.executeUpdate();

		
	}

	@Override
	public ArrayList<Dentists> listAllDentists() throws Exception {

		ArrayList <Dentists> dentists= new ArrayList<>();
		
		Statement stmt= manager.getConnection().createStatement();	
		
		String sql= "SELECT * FROM dentist";
		
		ResultSet rs = stmt.executeQuery(sql);
		
		while (rs.next()){
			
			int id = rs.getInt("id");
			String name = rs.getString("name");
			String bankAccount = rs.getString("bank account");
			String email = rs.getString("email");
			int mobile = rs.getInt("mobile");
			
			Dentists dentist = new Dentists (id, name, bankAccount, mobile, email);
			
			dentists.add(dentist);
		}
		
		rs.close();
		stmt.close();

		return dentists;
	}

	@Override
	public Dentists getDentistByName(String dName) throws Exception {


		Dentists dentist= null;
		
		String sql= "SELECT * FROM dentist"
				+ "WHERE name= ?";
		
		PreparedStatement prep= manager.getConnection().prepareStatement(sql);
		
		prep.setString(1, dName);
				
		ResultSet rs= prep.executeQuery();
		
		if(rs.next()) {
			
			int id=rs.getInt("id");
			String name= rs.getString("name");
			String bankAccount= rs.getString("bank account");
			String email= rs.getString("email");
			int mobile= rs.getInt("mobile");
			
			dentist= new Dentists(id, name, bankAccount,mobile, email);
			
		}

		rs.close();
		prep.close();
		
		return dentist;
	}
	
	
}
